### PR TITLE
Remove duplications in include_HEADERS.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix errors in "make install" like:
```
/usr/bin/install: will not overwrite just-created ‘/opt/sortmerna-2.1/include/gumbel_params.hpp’ with ‘./alp/gumbel_params.hpp’
```

Needed for https://github.com/bgruening/galaxytools/pull/295 (SortMeRNA Galaxy wrapper).

### CODE REVIEW

**Comment by ekopylova** [comment]
Thanks Nicola,
The changes look fine to me. I just set up Travis for building and testing new PRs, would it be possible for you to make a small change to your PR (ex. a note in the ChangeLog) and push again so Travis is activated?

**Comment by nsoranzo** [comment]
@ekopylova I've modified the commit message and force-pushed.

**Comment by bgruening** [comment]
@ekopylova can we have a new point release with this fix included?

**Comment by ekopylova** [comment]
I guess it wasn't included in the 2.1 release? We're working on a pull request with many changes to the code, including the addition of reading zip or gzip files. I was planning on releasing 2.2 once that is merged (early next week). Would that be fine?

**Comment by bgruening** [comment]
Yes, just want to make your Galaxy wrapper is up-to-date :)

Thanks!

**Comment by bebatut** [comment]
:+1: for the release (for Galaxy wrapper)
Thanks

**Comment by ekopylova** [comment]
Will make a new release as soon as this [PR](https://github.com/biocore/sortmerna/pull/111) is merged (reading gzipped input). Sorry for the delay, busy with multiple projects at the moment. Working on this now ..

**Comment by ekopylova** [comment]
I've made a new [release 2.1b](https://github.com/biocore/sortmerna/releases/tag/2.1b) that has this patch. Gzip support will be in the next release. Thanks!

**Pull request merged**
